### ISSUE TITLE
UBSAN violation in kj::Vector/ArrayBuilder? Also uninitialized variable in ArrayBuilder::disposer

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#1079]
The following lines of code:
```
      kj::Vector<int> fds;
      auto exports = connectionState->writeDescriptors(
          capTable.getTable(), callBuilder.getParams(), fds);
      message->setFds(fds.releaseAsArray());
```

in RpcRequest (rpc.c++) seem to trigger a violation but the problem appears to be in kj::Vector::releaseAsArray on an empty array (which is possible, for one example, if the cap table passed to `writeDescriptors` is empty).

```
capnproto/c++/src/kj/array.h:472:59: runtime error: reference binding to null pointer of type 'const kj::ArrayDisposer'
    #0 0x922f7a in kj::ArrayBuilder<int>::finish() capnproto/c++/src/kj/array.h:472:14
    #1 0x916a65 in kj::Vector<int>::releaseAsArray() capnproto/c++/src/kj/vector.h:70:20
    #2 0x891acb in capnp::_::(anonymous namespace)::RpcConnectionState::RpcRequest::setupSend(bool) capnproto/c++/src/capnp/rpc.c++:1828:27
    #3 0x89099b in capnp::_::(anonymous namespace)::RpcConnectionState::RpcRequest::sendInternal(bool) capnproto/c++/src/capnp/rpc.c++:1849:21
    #4 0x88f069 in capnp::_::(anonymous namespace)::RpcConnectionState::RpcRequest::send() capnproto/c++/src/capnp/rpc.c++:1718:27
```

I also noticed that on Windows disposer isn't NULL but that's because it's an uninitialized variable containing a garbage value. Namely the `ArrayBuilder()` and `ArrayBuilder(decltype(nullptr))` constructors don't initialize `disposer` to `nullptr`. If I explicitly default the disposer member variable to a default of `nullptr` then Windows has the same problem dereferencing a null pointer.

Stylistic curiosity. Why `decltype(nullptr)` vs `std::nullptr` from `cstdef`?

**Comment by dwrensha** [comment]
Related: #549, which was reverted in #578.

**Comment by kentonv** [comment]
I guess an easy fix would be to initialize the disposer pointer to `&NullArrayDisposer::instance`.

> Stylistic curiosity. Why decltype(nullptr) vs std::nullptr from cstdef?

KJ has ambitions to be independent of the C++ standard library, so when it's easy to avoid including a standard header I like to avoid it.
