### ISSUE TITLE
generated_header_support.h - BrandBindingFor_ generates schema-less brands for enums

### ISSUE THREAD

**Issue by alexrobomind** [capnproto/capnproto#1518]
Today I was stumbling about cases where I could not print branded structs if the brand parameter was bound to a `List({enum type})` via `KJ_DBG`. This happened due to BrandArgumentList receiving the enum binding with `schema==nullptr` and passing the binding to the constructor `Type::Type(schema::Type::Which)` (which would promptly reject the enum argument due to the missing type information).

After digging a bit into the schema generation facilities, I noticed something odd in generated_header_support.h:

When handling enums in `BrandBindingFor_`, the template specialization returns `{ 15, listDepth, nullptr }`. However, I would expect the correct binding here to be `{15, listDepth, schemas::EnumInfo<T>::schema->defaultBrand}` (analogous to `rawBrandedSchema<EnumType>()`).

I suspect that this makes enum lists generally unreliable to use in the dynamic API when used through the C++ types. I also assume this likely never caused an issue for the following reasons:
 - When using the dynamic API from a schema, SchemaLoader uses a different pathway (`SchemaLoader::Impl::makeDep`) to load the brand information
 - C++ lists do not need the brand information, they directly derive all they need from the C++ types.

 Is my suspicion correct, or am I chasing down the wrong avenue?

**Comment by kentonv** [comment]
Hmm, it's been so long since I wrote this code that you probably know it better than me right now.

Of course, all specializations of a generic enum are identical, so it's a little weird to think about branded enums in the first place. It's possible that while writing some code I assumed that generic enums don't exist, while other code I decided they do exist just for consistency?

**Comment by alexrobomind** [comment]
It is not just the brand information that is missing (I don't think that this would be an issue, as enums are entirely unbranded). The code does not pass back any schema information at all (not even the schema node itself), which means that the list actually doesn't know what enum it is wrapping.

**Comment by alexrobomind** [comment]
I've made a reproduction example to show the exact issue. Stack trace entry 6 shows the nature of the issue, as it contains an invalid binding. The binding is of type enum, but the schema is a nullptr (when it should point to the enum's schema). This matches the behavior of the BrandBindingFor_ template, so I suspect it as the root culprit.

```
#include <capnp/schema.capnp.h>
#include <capnp/persistent.capnp.h>
#include <capnp/schema.h>
#include <capnp/orphan.h>

#include <capnp/message.h>

#include <kj/debug.h>

int main() {
	using namespace capnp;
	
	// Persistent<...>::SaveParams and ::SaveResults are the only generic types in the standard library
	using ListType = List<schema::ElementSize>;
	using Branded = Persistent<AnyPointer, ListType>::SaveParams;
	
	MallocMessageBuilder msg;
	auto root = msg.initRoot<Branded>();
	
	KJ_DBG(root); // Works
	
	auto data = root.initSealFor(1);
	data.set(0, schema::ElementSize::TWO_BYTES);
	
	KJ_DBG(root); // KABOOM
	
	return 0;
}

```

Yields:

```
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  capnp/schema.h:896: failed: expected primitive != schema::Type::STRUCT && primitive != schema::Type::ENUM && primitive != schema::Type::INTERFACE && primitive != schema::Type::LIST
stack: 557a0b63dd07 557a0b616d83 557a0b61147f 557a0b610f0b 557a0b611249 557a0b611c4c 557a0b61f324 557a0b5fe6a8 557a0b5febd0 557a0b5ff36e 557a0b5d1acc 557a0b5d19d0 557a0b5d18e8 557a0b5d159a 557a0b5d12d1 557a0b5d0f90 557a0b5d0aa2 7efd2c3d3082 557a0b5d090d

```
Stack trace:

```
#0  0x00007ffff7e64672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#1  0x00005555555ce97f in kj::ExceptionCallback::RootExceptionCallback::onFatalException (this=0x55555565c130, exception=...) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/exception.c++:1048
No locals.
#2  0x00005555555cd052 in kj::throwFatalException (exception=..., ignoreCount=1) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/exception.c++:1135
No locals.
#3  0x00005555555c7277 in kj::_::Debug::Fault::fatal (this=0x7fffffffd150) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/debug.c++:371
        [ Removed due to excessive length ]
#4  0x00005555555c5d08 in kj::_::inlineRequireFailure (file=0x555555605098 "/mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/schema.h", line=896,
    expectation=0x5555556050f8 "primitive != schema::Type::STRUCT && primitive != schema::Type::ENUM && primitive != schema::Type::INTERFACE && primitive != schema::Type::LIST", macroArgs=0x5555556050f7 "", message=0x0)
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/common.c++:33
        f = {exception = 0x0}
#5  0x000055555559ed84 in capnp::Type::Type (this=0x7fffffffd1d0, primitive=capnp::schema::Type::ENUM) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/schema.h:896
No locals.
#6  0x0000555555599480 in capnp::Schema::BrandArgumentList::operator[] (this=0x7fffffffd240, index=1) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/schema.c++:441
        binding = @0x5555555fe190: {which = 15 '\017', isImplicitParameter = false, listDepth = 1, paramIndex = 0, {schema = 0x0, scopeId = 0}}
        result = {baseType = capnp::schema::Type::VOID, listDepth = 0 '\000', isImplicitParam = 85, {paramIndex = 21845, anyPointerKind = 21845}, {schema = 0x0, scopeId = 0}}
#7  0x0000555555598f0c in capnp::Schema::getBrandBinding (this=0x7fffffffd520, scopeId=14468694717054801553, index=1) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/schema.c++:357
No locals.
#8  0x000055555559924a in capnp::Schema::interpretType (this=0x7fffffffd520, proto=..., location=16777216) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/schema.c++:403
        param = {_reader = {segment = 0x0, capTable = 0x0, data = 0x5555555fe520 <capnp::schemas::b_f76fba59183073a5+224>, pointers = 0x5555555fe538 <capnp::schemas::b_f76fba59183073a5+248>, dataSize = 192, pointerCount = 1,
            nestingLimit = 2147483643}}
        anyPointer = {_reader = {segment = 0x0, capTable = 0x0, data = 0x5555555fe520 <capnp::schemas::b_f76fba59183073a5+224>, pointers = 0x5555555fe538 <capnp::schemas::b_f76fba59183073a5+248>, dataSize = 192, pointerCount = 1,
            nestingLimit = 2147483643}}
#9  0x0000555555599c4d in capnp::StructSchema::Field::getType (this=0x7fffffffd520) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/schema.c++:536
        proto = {_reader = {segment = 0x0, capTable = 0x0, data = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160>, pointers = 0x5555555fe4f8 <capnp::schemas::b_f76fba59183073a5+184>, dataSize = 192, pointerCount = 4,
            nestingLimit = 2147483644}}
        location = 16777216
#10 0x00005555555a7325 in capnp::DynamicStruct::Reader::has (this=0x7fffffffd620, field=..., mode=capnp::HasMode::NON_NULL) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/dynamic.c++:440
        proto = {_reader = {segment = 0x0, capTable = 0x0, data = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160>, pointers = 0x5555555fe4f8 <capnp::schemas::b_f76fba59183073a5+184>, dataSize = 192, pointerCount = 4,
            nestingLimit = 2147483644}}
        slot = {_reader = {segment = 0x0, capTable = 0x0, data = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160>, pointers = 0x5555555fe4f8 <capnp::schemas::b_f76fba59183073a5+184>, dataSize = 192, pointerCount = 4,
            nestingLimit = 2147483644}}
        type = {baseType = -10312, listDepth = 255 '\377', isImplicitParam = 255, {paramIndex = 32767, anyPointerKind = 32767}, {schema = 0x7fffffffd4e0, scopeId = 140737488344288}}
#11 0x00005555555866a9 in capnp::(anonymous namespace)::print (value=..., which=capnp::schema::Type::STRUCT, indent=..., mode=capnp::(anonymous namespace)::BARE)
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/stringify.c++:200
        field = {parent = {<capnp::Schema> = {
              raw = 0x555555645ae0 <capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::_capnpPrivate::specificBrand>}, <No data fields>}, index = 0, proto = {
            _reader = {segment = 0x0, capTable = 0x0, data = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160>, pointers = 0x5555555fe4f8 <capnp::schemas::b_f76fba59183073a5+184>, dataSize = 192, pointerCount = 4,
              nestingLimit = 2147483644}}}
        __for_range = @0x7fffffffd7b0: {parent = {<capnp::Schema> = {
              raw = 0x555555645ae0 <capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::_capnpPrivate::specificBrand>}, <No data fields>}, list = {reader = {
              segment = 0x0, capTable = 0x0, ptr = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160> "", elementCount = 1, step = 448, structDataSize = 192, structPointerCount = 4,
              elementSize = capnp::ElementSize::INLINE_COMPOSITE, nestingLimit = 2147483645}}, indices = 0x5555555fe55a <capnp::schemas::i_f76fba59183073a5>, size_ = 1}
        __for_begin = {container = 0x7fffffffd7b0, index = 0}
        __for_end = {container = 0x7fffffffd7b0, index = 1}
        printedFields = {builder = {ptr = 0x55555565bec0, pos = 0x55555565bec0, endPtr = 0x55555565bef8, disposer = 0x555555646488 <kj::_::HeapArrayDisposer::instance>}}
        which = {ptr = {isSet = false, {value = {parent = {<capnp::Schema> = {raw = 0x5555555790f2 <kj::_::DebugExpression<bool>::DebugExpression(bool&&)+32>}, <No data fields>}, index = 4294957184, proto = {_reader = {
                    segment = 0x7fffffffd847, capTable = 0x7fffffffd850, data = 0x55555556ee27 <kj::_::DebugExpressionStart::operator<< <bool>(bool&&) const+65>, pointers = 0x7fffffffd880, dataSize = 1432375791, pointerCount = 21845,
                    nestingLimit = 1432640224}}}}}}
        unionValue = {size_ = 0, text = {content = {ptr = 0x0, size_ = 0, disposer = 0x0}}, branches = {ptr = 0x0, size_ = 0, disposer = 0x0}}
        structValue = {schema = {<capnp::Schema> = {
--Type <RET> for more, q to quit, c to continue without paging--
              raw = 0x555555645ae0 <capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::_capnpPrivate::specificBrand>}, <No data fields>}, reader = {
            segment = 0x7fffffffdc88, capTable = 0x7fffffffdc60, data = 0x555555659eb8, pointers = 0x555555659eb8, dataSize = 0, pointerCount = 1, nestingLimit = 2147483647}}
        unionFields = {parent = {<capnp::Schema> = {
              raw = 0x555555645ae0 <capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::_capnpPrivate::specificBrand>}, <No data fields>}, list = {reader = {
              segment = 0x0, capTable = 0x0, ptr = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160> "", elementCount = 1, step = 448, structDataSize = 192, structPointerCount = 4,
              elementSize = capnp::ElementSize::INLINE_COMPOSITE, nestingLimit = 2147483645}}, indices = 0x5555555fe55a <capnp::schemas::i_f76fba59183073a5>, size_ = 0}
        nonUnionFields = {parent = {<capnp::Schema> = {
              raw = 0x555555645ae0 <capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::_capnpPrivate::specificBrand>}, <No data fields>}, list = {reader = {
              segment = 0x0, capTable = 0x0, ptr = 0x5555555fe4e0 <capnp::schemas::b_f76fba59183073a5+160> "", elementCount = 1, step = 448, structDataSize = 192, structPointerCount = 4,
              elementSize = capnp::ElementSize::INLINE_COMPOSITE, nestingLimit = 2147483645}}, indices = 0x5555555fe55a <capnp::schemas::i_f76fba59183073a5>, size_ = 1}
#12 0x0000555555586bd1 in capnp::(anonymous namespace)::stringify (value=...) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/stringify.c++:228
No locals.
#13 0x000055555558736f in capnp::_::structString (reader=..., schema=...) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/stringify.c++:255
No locals.
#14 0x0000555555559acd in capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::Reader::toString (this=0x7fffffffda30)
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/persistent.capnp.h:168
No locals.
#15 0x00005555555599d1 in capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::Builder::toString (this=0x7fffffffdbe0)
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/capnp/persistent.capnp.h:206
No locals.
#16 0x00005555555598e9 in kj::_::Stringifier::operator*<capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::Builder&, kj::StringTree> (
    this=0x5555555fe022 <kj::_::STR>, value=...) at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/string.h:429
No locals.
#17 0x000055555555959b in kj::toCharSequence<capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::Builder&> (value=...)
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/string.h:446
No locals.
#18 0x00005555555592d2 in kj::str<capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::Builder&> ()
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/string.h:463
No locals.
#19 0x0000555555558f91 in kj::_::Debug::log<capnp::Persistent<capnp::AnyPointer, capnp::List<capnp::schemas::ElementSize_d1958f7dba521926, (capnp::Kind)2> >::SaveParams::Builder&> (
    file=0x5555555fe138 "/mnt/c/Users/Knieps/Documents/repos/fsc/src/c++/tools/brandedEnums.cpp", line=20, severity=kj::LogSeverity::DBG, macroArgs=0x5555555fe12d "root")
    at /mnt/c/Users/Knieps/Documents/repos/fsc/build-linux/_deps/capnproto-src/c++/src/kj/debug.h:491
        argValues = {{content = {ptr = 0x7fffffffdbc0 "P\335\377\377\377\177", size_ = 93824992251691, disposer = 0x7fffffffdc40}}}
#20 0x0000555555558aa3 in main () at /mnt/c/Users/Knieps/Documents/repos/fsc/src/c++/tools/brandedEnums.cpp:20
        _kj_shouldLog = true
        msg = {<capnp::MessageBuilder> = {_vptr.MessageBuilder = 0x555555645de0 <vtable for capnp::MallocMessageBuilder+16>, arenaSpace = {0x555555646008 <vtable for capnp::_::BuilderArena+16>, 0x7fffffffdc40, 0xffffffffffffffff,
              0x555555645fe0 <vtable for capnp::_::BuilderArena::LocalCapTable+16>, 0x0, 0x0, 0x0, 0x555555646480 <kj::NullArrayDisposer::instance>, 0x7fffffffdc48, 0x0, 0x555555659eb0, 0x400, 0x7fffffffdc58, 0x555555659ec0,
              0xffffffffffffff00, 0x0, 0x0, 0x0, 0x0, 0x7fffffffdc88, 0x0, 0x280}, allocatedArena = true}, nextSize = 1024, allocationStrategy = capnp::AllocationStrategy::GROW_HEURISTICALLY, ownFirstSegment = true,
          returnedFirstSegment = true, firstSegment = 0x555555659eb0, moreSegments = {builder = {ptr = 0x0, pos = 0x0, endPtr = 0x0, disposer = 0x555555646480 <kj::NullArrayDisposer::instance>}}}
        root = {_builder = {<kj::DisallowConstCopy> = {<No data fields>}, segment = 0x7fffffffdc88, capTable = 0x7fffffffdc60, data = 0x555555659eb8, pointers = 0x555555659eb8, dataSize = 0, pointerCount = 1}}
        data = {builder = {<kj::DisallowConstCopy> = {<No data fields>}, segment = 0x0, capTable = 0x7ffff7cc1371 <__GI___sbrk+145>, ptr = 0x7ffff7d99b80 <main_arena> "", elementCount = 656, step = 0, structDataSize = 0,
            structPointerCount = 0, elementSize = capnp::ElementSize::VOID}}
```
