### ISSUE TITLE
Porting capnproto to emscripten. Work in progress. Is it possible without signals?

### ISSUE THREAD

**Issue by germandiagogomez** [capnproto/capnproto#1750]
Hello everyone.

I am using capnproto version 0.10.3. Congrats for this great library. It is working great so far in native environments.

## Current problem: cross-compiling

However, I need to take things a step further: I am trying to compile the library for emscripten. I need to use my client side on emscripten, but also part of server-side capnproto, since my little app has bi-directional communication: requests from the client and a subscriber object is sent to the server so that notifications arrive on my end. Porting all to json and encoding/decoding can be a way to handle it, but compiling capnproto for emscripten would be ideal.

Porting to emscripten via the Conan recipe and after further build system inspection has been more challenging for a few  reasons:

- Conan offers an autotools-based toolchain that seemed not to work. I could not pass the correct cross compilation files.
- CMake seems to be broken in the build machine vs host machine department when cross-compiling. This ruins building capnpc tool or the build tools I need to go forwad.

### Cross-compilation progress 

Given these problems, and since I am using Meson build system for my own project, I started a port to Meson build system that is mostly done. What I can do so far:

- Correctly compile tools for the build machine.
-  Correctly compile libraries in build and host mode for whoever needs to consume them (capnpc, libraries, etc.)
- Correctly compile *almost* everything for emscripten, except for the lack of, apparently, sigsuspend implementation in emscripten when linking.
- All the build system has been ported from CMake except the capnp lite sections. The options for activating tests, fibers, etc. are mirrored in the meson.options file.
- I *expect* (but not there yet) to be able to run all tests via node.js. This can be a good witness of how well the lib is working.

## What do I need to make capnproto fully work in emscripten?

Besides *sigsuspend* implementation, is there any other stuff I need to be aware of when porting to emscripten that will not work? BTW, I have an issue open requesting sigsuspend implementation for emscripten, but no reply so far: https://github.com/emscripten-core/emscripten/issues/19880

## Tests results so far in Web Assembly

This is the results from the tests I run so far, seems to have a few things broken:

```

/Users/germandiago/capnproto/build-emscripten/c++/src/kj/kj-tests.js:148
      throw ex;
      ^
Exception [WebAssembly.Exception] {
  message: [
    'kj::ExceptionImpl',
    'kj/exception.c++:635: unimplemented: sigaltstack(&stack, nullptr): Function not implemented'
  ]
}

Node.js v20.5.0
/Users/germandiago/capnproto/build-emscripten/c++/src/kj/kj-tests.worker.js:24
  parentPort.on('message', (data) => onmessage({ data: data }));
             ^

TypeError: Cannot read properties of null (reading 'on')
    at Object.<anonymous> (/Users/germandiago/capnproto/build-emscripten/c++/src/kj/kj-tests.worker.js:24:14)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.0

/Users/germandiago/capnproto/build-emscripten/c++/src/capnp/capnp-tests.js:148
      throw ex;
      ^
Exception [WebAssembly.Exception] {
  message: [
    'kj::ExceptionImpl',
    'kj/exception.c++:635: unimplemented: sigaltstack(&stack, nullptr): Function not implemented'
  ]
}

Node.js v20.5.0
/Users/germandiago/capnproto/build-emscripten/c++/src/capnp/capnp-evolution-tests.worker.js:24
  parentPort.on('message', (data) => onmessage({ data: data }));
             ^

TypeError: Cannot read properties of null (reading 'on')
    at Object.<anonymous> (/Users/germandiago/capnproto/build-emscripten/c++/src/capnp/capnp-evolution-tests.worker.js:24:14)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.0
/Users/germandiago/capnproto/build-emscripten/c++/src/capnp/capnp-tests.worker.js:24
  parentPort.on('message', (data) => onmessage({ data: data }));
             ^

TypeError: Cannot read properties of null (reading 'on')
    at Object.<anonymous> (/Users/germandiago/capnproto/build-emscripten/c++/src/capnp/capnp-tests.worker.js:24:14)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.0

/Users/germandiago/capnproto/build-emscripten/c++/src/capnp/capnp-evolution-tests.js:148
      throw ex;
      ^
Exception [WebAssembly.Exception] {
  message: [
    'kj::ExceptionImpl',
    'kj/exception.c++:635: unimplemented: sigaltstack(&stack, nullptr): Function not implemented'
  ]
}

Node.js v20.5.0
```

## Branch to play with

I published a forked branch of what I have so far in this fork:  https://github.com/germandiagogomez/capnproto/tree/feature/add-meson-build-system-to-capnp-0.10.3

You need to point to your compiled emscripten dependencies in `pkg_config_path` variable in meson/cross/emscripten.ini if needed and your native pkg-config should find native dependencies. You will also need 
that meson detects a c++ compiler on your side for the build machine.

Follow these instruction to test:

 1. use `./bootstrap-emscripten.sh`. This will download the sdk and activate it and create a `emscripten_constants.ini` file in your `meson/cross` directory to point to your toolchain correctly.
 2. issue this command: `meson setup -Dwith_openssl=disabled -Dwith_fibers=disabled -Dwith_zlib=disabled -Dbuild_testing=true --cross-file meson/cross/emscripten_constants.ini --cross-file meson/cross/emscripten.ini build-emscripten`
 
If all dependencies are found, things won't still compile clean, at least in MacOS, but most will do. However, you will have a bunch of javascript tests waiting for you. To run them, you can do the following (assuming node is installed):

```
find build-emscripten -name '*.js'| grep -v sanitycheck| while read entry; do node $entry; done
```

You can set the options via `meson configure -Dyour_option=value build-emscripten` if you want to change something.

Hope it can be a start point if it is feasible to do a port.

**Comment by germandiagogomez** [comment]
I am relatively sure I hit a wall with the signals in emscripten, seems those seem impossible to workaround in some cases.

Would there be any alternative implementation for capnproto which can be proposed? Not sure how it would work internally or even if it can, but basically it would be an implementation that cannot use pre-emption from signals and probably cannot use `sigaltstack`.

Any ideas on such a design?

Right now I am work-arounding it by using json-rpc and using a proxy client in the server side for emscripten version of my software. If everything worked with a single codebase it would be great.

I can collaborate on the effort, btw.

**Comment by kentonv** [comment]
Hi Germán,

Cap'n Proto does not actually use signals. `kj/async-unix.{h,c++}` provides APIs to wait on signals along with every other type of event because applications sometimes need to be able to wait on signals. Obviously in emscripten, there are no signals, so apps don't need those APIs. I imagine the solution were would be to wrap all signal-related APIs in `if !__EMSCRIPTEN__`.

I'd expect there's a lot of other stuff that needs similar treatment on Emscripten. But the core code shouldn't require anything particularly OS-specific.

> I started a port to Meson build system

Just a warning, we already support four different build systems (autotools, cmake, bazel, ekam) and it's fairly painful. We're not likely to accept a fifth.

**Comment by kiinoo** [comment]
i built the generated code for wasm successfully, but unfortunately current js/ts code generator is either out of date or having problems. So i quit using capnproto entirely..
